
---

## 📄 `docker-compose.yml`
```yaml
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
